apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: java-app-pipeline
    name: java-app-pipeline
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/roshans416/openshift-s2i-demo.git
      type: Git
    strategy:
      jenkinsPipelineStrategy: {}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: 67OJMj8iWqHe7GKfEIbO
      type: GitHub
    - generic:
        secret: l567UUNKSs3HWRYTweP1
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
kind: List
metadata: {}
